name: Deploy

on:
  workflow_call:
  workflow_dispatch:

env:
  deployment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Upload to Deno Deploy
        id: deploy
        uses: denoland/deployctl@v1
        with:
          project: denopendabot
          entrypoint: ./app.ts

      - name: Set the deployment ID on Upstash
        run: >
          curl -X POST -d '${{ steps.deploy.outputs.deployment-id }}'
          ${{ secrets.UPSTASH_REDIS_REST_URL }}/set/${{ env.deployment }}-id
          -H "Authorization: Bearer ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}"

      - name: Set the deployment URL on Upstash
        run: >
          curl -X POST -d '${{ steps.deploy.outputs.url }}'
          ${{ secrets.UPSTASH_REDIS_REST_URL }}/set/${{ env.deployment }}-url
          -H "Authorization: Bearer ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}"
